name: Validate on Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  security-checks:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      max-parallel: 5
      matrix:
        image-name:
          - general-tools
          - php-pdo
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build Local Image
        uses: eschercloudai/container-security-action@v0.0.2
        if: github.event_name == 'pull_request'
        with:
          use-dockerhub: true
          image-repo: "drewviles"
          repo-username: ${{ secrets.DOCKER_USER }}
          repo-password: ${{ secrets.DOCKER_PASSWORD }}
          image-name: ${{ matrix.image-name }}
          image-tag: ${{ github.ref_name }}
          check-severity: CRITICAL
          trivyignore-from-s3: false
          publish-image: false
          cosign-private-key: ${{secrets.COSIGN_KEY}}
          cosign-password: ${{secrets.COSIGN_PASSWORD}}
          cosign-tlog: false
          dockerfile-path: ${{ matrix.image-name }}
