name: Validate on Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  security-checks:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      max-parallel: 5
      matrix:
        image-name:
          - samba
          - php-pdo
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build Local Image
        uses: drewbernetes/container-security-action@v0.0.4
        if: github.event_name == 'pull_request'
        with:
          image-repo: "drewviles"
          repo-username: ${{ secrets.DOCKER_USER }}
          repo-password: ${{ secrets.DOCKER_PASSWORD }}
          image-name: ${{ matrix.image-name }}
          image-tag: v0.0.0
          check-severity: "HIGH,CRITICAL"
          trivyignore-from-s3: false
          publish-image: false
          cosign-private-key: ${{secrets.COSIGN_KEY}}
          cosign-password: ${{secrets.COSIGN_PASSWORD}}
          cosign-tlog: false
          dockerfile-path: ${{ matrix.image-name }}
